### ISSUE TITLE
Bullet points don't show in the template

### ISSUE THREAD

**Issue by sulthan-ahmed** [UKHomeOfficeForms/hof-middleware-markdown#2]
Unless I'm doing something wrong, it seems like bullets aren't appearing in the template e.g.

```* Home Office reference number

* passport number
```
Displays

```Home Office reference number

passport number
```

**Comment by lennym** [comment]
This is nothing to do with markdown, but with some css in `hof-frontend-toolkit` that disables default styles. If you update your version of that module then you will see it is resolved.

See https://github.com/UKHomeOfficeForms/hof-frontend-toolkit/commit/3bb029468ea0a4b0c86b87f0ad12c1cc2e7c3b01

**Comment by sulthan-ahmed** [comment]
👍
